---
title: "R Final Project ('The Office')"
author: "McKenzie Price"
format: html
execute: 
  echo: false
  warning: false
---
```{r}
library(schrute)
library(tidyverse)
library(here)
library(gtsummary)

office_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv')

# save the complete-case data
saveRDS(office_ratings, here::here("office_data.rds"))

office_data <- readRDS(here::here("office_data.rds"))
```

```{r}
#| label: tbl-one
#| tbl-cap: "**Summary of ‘The Office’ Episodes by Season**"
tbl_summary(
	office_data,
	by = season,
	include = c(imdb_rating, total_votes, air_date),
  label = list(
  	imdb_rating ~ "IMDB Rating",
  	total_votes ~ "Total Votes",
  	air_date ~ "Air Date"),

	statistic = list(
		imdb_rating ~ "{mean} ({min}, {max})",
		total_votes ~ "{sum}",
		air_date ~ "({min}) to ({max})"),

missing_text = "Missing")

imdb_ratings <- office_data$imdb_rating

imdb_mean <- function(imdb_ratings) {
	n <- length(imdb_ratings)
	mean_val <- sum(imdb_ratings) / n
	return(mean_val)
}

total_mean <- imdb_mean(imdb_ratings)
```
@tbl-one is a descriptive table summarizing 'The Office' episodes by season. The table includes the average, minimum and maximum IMBD ratings, the total votes, and start to finish air dates of each season. 

The average IMDB rating for all seasons of 'The Office' is `r total_mean`. 
inline_text(table1, variable = "total_votes", column = "stat_0")

```{r}
#| label: tbl-two
#| tbl-cap: "**Poisson Regression Analysis**"
poisson_model <- glm(total_votes ~ imdb_rating + season,
										 family = poisson,
										 data = office_data)
tbl_regression(
	poisson_model,
	exponentiate = TRUE,
	label = list(
		imdb_rating ~ "IMDB Rating",
		season ~ "Season"
	)) 
```

```{r}
#| label: fig-one
#| fig-cap: "A box plot showing the "
boxplot(imdb_rating ~ season, data = office_data,
				main = "Box Plot Comparing 'The Office' IMDB Ratings by Season",
				xlab = "Season",
				ylab = "IMDB Rating",
				outline = TRUE)
```


